config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'sessions/new'
  get 'users/new'
  get '/jobs', to: 'jobs#jobs_list'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    resources :jobs, only: [:new, :create, :index]
  end
  resources :jobs, only: [:show]
  resources :job_applications, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  def get_job_applicant(job)
    applicant_names = []
    job_application_user_ids = JobApplication.where(job_id: job.id).pluck(:user_id)
    job_application_user_ids.each do |user_id|
      applicant_names << User.find_by_id(user_id).name
    end
    applicant_names.join(' , ')
  end

end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  belongs_to :job
  belongs_to :applicant, class_name: 'User', foreign_key: 'user_id'
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum:50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX},
    uniqueness: { case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: { minimum: 6}
  has_many :jobs, :foreign_key => 'user_id', :dependent => :destroy
  has_many :job_applications, :foreign_key => 'user_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController

  def create
    @job_application = JobApplication.new(job_application_params)
    if @job_application.save
      flash[:success] = 'Your application has been submitted successfully'
      redirect_to job_path(params[:job_application][:job_id])
    else
      render_to new_job_application_path, alert: "Oops, there was a problem, please try again"
    end
  end

  private

  def job_application_params
    params.require(:job_application).permit(:user_id, :job_id)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def new
    @job = Job.new
  end

  def jobs_list
    @jobs_list = Job.all
  end

  def index
    @company_jobs = current_user.jobs
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      flash[:success] = 'Job Successfully Created'
      redirect_to job_path(@job.id)
    else
      render 'new'
    end
  end

  def show
    @job = Job.find(params[:id])
    @job_application = JobApplication.new
    @job_applied = JobApplication.find_by_user_id_and_job_id(current_user.id, params[:id])
  end

  def job_params
    params.require(:job).permit(:title, :description, :employer_name, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @jobs_created = @user.jobs
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'Welcome to job board app'
      redirect_to @user
    else
      render 'new'
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title='')
    base_title = "Ruby on Rails Tutorial Sample App"
     if page_title.empty?
       base_title
     else
       page_title + " | " + base_title
     end
   end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/jobs/index.html.erb
<h1>My Jobs List</h1>
<% @company_jobs.each do |company_job| %>
  <ul>
    <li>  <%= link_to company_job.title, job_path(company_job.id) %></li>
    <li> Applied by - <%= "#{company_job.get_job_applicant(company_job)}" %> </li>
  </ul>
<% end %>
</table>

app/views/jobs/jobs_list.html.erb
<h1>Listing Jobs</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Employer Name</th>
  </tr>
  <% @jobs_list.each do |job_list| %>
    <tr>
      <td><%= job_list.title %></td>
      <td><%= job_list.employer_name %></td>
      <td><%= link_to 'Show', job_list %></td>
    </tr>
  <% end %>
</table>

app/views/jobs/new.html.erb
<% provide(:title, 'Create Jobs') %>
<h1>Create Jobs</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@job, url: user_jobs_path) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
      <%= f.label :employer_name %>
      <%= f.text_field :employer_name, class: 'form-control' %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.submit "Create Job", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        Job Title: <span><%= @job.title %><span>
          </h1>
          <br/>
          <h1>
            Job Description: <span><%= @job.description %><span>
              </h1>
              <br/>
              <h1>
                Employer Name: <span><%= @job.employer_name %><span>
                  </h1>
                  <br/>
                  <% if current_user.role != 'company' %>
                    <%if @job_applied.nil? %>
                      <%= form_for(@job_application, url: job_applications_path) do |f| %>
                        <%= f.hidden_field :user_id, value: current_user.id %>
                        <%= f.hidden_field :job_id, value: params[:id] %>
                        <%= f.submit "Apply", class: "btn btn-primary" %>
                      <% end %>
                    <% end %>
                  <% end %>
                </section>
              </aside>
            </div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Job Board", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Home", current_user%></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign up", root_path%></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Job Board </title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Job Board App</h1>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/errors' %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <div class='col-md-1' >
        <%= f.check_box :role, {}, "company", "job-seeker" %>
      </div>
      <div class='col-md-5' >
        <%= f.label :role, "Company" %>
      </div>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.email %>
      </h1>
      <% if @user.role == 'company' %>
        <%= link_to "Create Job", new_user_job_path(@user) %>
      <% else %>
        <%= link_to "Show Jobs", jobs_path %>
      <% end %>
      <% if @jobs_created.count > 0 %>
        <%= link_to "My Jobs", user_jobs_path(@user) %>
      <% end %>
    </section>
  </aside>
</div>